package grade

import org.junit.jupiter.api.*

import grade.AbstractModule
import core.Server
import model.Response
import model.Table

class Module2 extends AbstractModule {
	@BeforeAll
	static void setup() {
		module_tag = 'M2'
		
		query_data = [
			// PREREQUISITES
			[ true,  'CREATE TABLE table_1 (ps STRING PRIMARY, i INTEGER, b BOOLEAN)', 'insertion depends on table creation' ],
			[ true,  'CREATE TABLE table_2 (s STRING, pi INTEGER PRIMARY, b BOOLEAN)', 'insertion depends on table creation' ],
			[ true,  'CREATE TABLE table_3 (s STRING, i INTEGER, pb BOOLEAN PRIMARY)', 'insertion depends on table creation' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: REORDERING
			[ true,  'INSERT INTO table_1 (ps, b, i) VALUES ("a1", false, 2)', 'reordering defined columns is allowed' ],
			[ true,  'INSERT INTO table_1 (i, ps, b) VALUES (3, "a4", true)', 'reordering defined columns is allowed' ],
			[ true,  'INSERT INTO table_1 (b, ps, i) VALUES (false, "a5", 6)', 'reordering defined columns is allowed' ],
			[ true,  'INSERT INTO table_1 (i, b, ps) VALUES (7, true, "a8")', 'reordering defined columns is allowed' ],
			[ true,  'INSERT INTO table_1 (b, i, ps) VALUES (false, 9, "a10")', 'reordering defined columns is allowed' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: OMISSION
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("b1", 2)', 'omitting columns is allowed' ],
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("b3", true)', 'omitting columns is allowed' ],
			[ true,  'INSERT INTO table_1 (i, ps) VALUES (4, "b5")', 'omitting columns is allowed' ],
			[ true,  'INSERT INTO table_1 (b, ps) VALUES (false, "b6")', 'omitting columns is allowed' ],
			[ true,  'INSERT INTO table_1 (ps) VALUES ("b7")', 'omitting columns is allowed' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: COLUMNS AND VALUES
			[ false, 'INSERT INTO table_1 (ps, i, b, i) VALUES ("c1", 2, true, 3)', 'column names cannot be repeated' ],
			[ false, 'INSERT INTO table_1 (ps, ps) VALUES ("c4", "c5")', 'column names cannot be repeated' ],
			[ false, 'INSERT INTO table_1 () VALUES ()', 'at least one column must be defined' ],
			[ false, 'INSERT INTO table_1 (ps, i, b) VALUES ("c6", 7, false, 8)', 'the number of values must match the number of columns' ],
			[ false, 'INSERT INTO table_1 (ps, i, b) VALUES ("c9", 10)', 'the number of values must match the number of columns' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: STRINGS
			[ true,  'INSERT INTO table_1 (ps) VALUES ("0 d1+d2? d3! ")', 'strings support arbitrary whitespace and non-alphanumeric symbols' ],
			[ true,  'INSERT INTO table_1 (ps) VALUES ("456")', 'strings can contain integer-like text' ],
			[ true,  'INSERT INTO table_1 (ps) VALUES ("null")', 'strings can contain keyword-like text' ],
			[ true,  'INSERT INTO table_1 (ps) VALUES ("")', 'strings can be empty' ],
			[ false, 'INSERT INTO table_1 (ps) VALUES (""")', 'strings cannot contain quotation marks' ],
			[ false, 'INSERT INTO table_1 (ps) VALUES (7)', 'string columns cannot accept integer literals' ],
			[ false, 'INSERT INTO table_1 (ps) VALUES (true)', 'string columns cannot accept boolean literals' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: INTEGERS
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("e1", -200)', 'negative integer literals are supported' ],
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("e3", 0)', 'zero is a valid integer literal' ],
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("e4", 500)', 'positive integer literals are supported' ],
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("e6", +700)', 'optional positive sign is supported' ],
			[ true,  'INSERT INTO table_1 (ps, i) VALUES ("e8", null)', 'integers can be null' ],
			[ false, 'INSERT INTO table_1 (ps, i) VALUES ("e9", 010)', 'leading zeroes are not supported' ],
			[ false, 'INSERT INTO table_1 (ps, i) VALUES ("e11", 12.0)', 'decimal points are not supported' ],
			[ false, 'INSERT INTO table_1 (ps, i) VALUES ("e13", "14")', 'integer columns cannot accept string literals' ],
			[ false, 'INSERT INTO table_1 (ps, i) VALUES ("e15", true)', 'integer columns cannot accept boolean literals' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: BOOLEANS
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("f1", true)', 'any case boolean literals are allowed' ],
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("f2", false)', 'any case boolean literals are allowed' ],
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("f3", TRUE)', 'any case boolean literals are allowed' ],
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("f4", False)', 'any case boolean literals are allowed' ],
			[ true,  'INSERT INTO table_1 (ps, b) VALUES ("f5", NuLl)', 'booleans can be null and null can be any case' ],
			[ false, 'INSERT INTO table_1 (ps, b) VALUES ("f6", "true")', 'boolean columns cannot accept string literals' ],
			[ false, 'INSERT INTO table_1 (ps, b) VALUES ("f7", 8)', 'boolean columns cannot accept integer literals' ],
			
			// INSERT/REPLACE INTO, SYNTAX AND SEMANTICS: STRING PRIMARY, ZERO INDEX
			[ false, 'INSERT INTO table_1 (i, b) VALUES (1, true)', 'primary column cannot be omitted' ],
			[ false, 'INSERT INTO table_1 (ps) VALUES (null)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_1 (ps, i, b) VALUES (null, 2, false)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_1 (ps, i, b) VALUES ("g3", 4, true); INSERT INTO table_1 (ps, i, b) VALUES ("g3", 5, false)', 'different rows may not share the same primary column value' ],
			[ true,  'INSERT INTO table_1 (ps, i, b) VALUES ("g6", 7, true); REPLACE INTO table_1 (ps, i, b) VALUES ("g6", 8, false)', 'a row can be replaced by a row with the same primary column value' ],
			
			// INSERT/REPLACE INTO, SYNTAX AND SEMANTICS: INTEGER PRIMARY, NON-ZERO INDEX
			[ true,  'INSERT INTO table_2 (s, pi, b) VALUES ("h1", 2, true)', 'primary column need not be leftmost' ],
			[ true,  'INSERT INTO table_2 (b, pi, s) VALUES (false, 3, "h4")', 'primary column need not be leftmost' ],
			[ true,  'INSERT INTO table_2 (s, b, pi) VALUES ("h5", false, 6)', 'primary column need not be leftmost' ],
			[ true,  'INSERT INTO table_2 (b, s, pi) VALUES (false, "h7", 8)', 'primary column need not be leftmost' ],
			[ false, 'INSERT INTO table_2 (s, b) VALUES ("h9", true)', 'primary column cannot be omitted' ],
			[ false, 'INSERT INTO table_2 (pi) VALUES (null)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_2 (s, pi, b) VALUES ("h10", null, false)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_2 (s, pi, b) VALUES ("h11", 12, true); INSERT INTO table_2 (s, pi, b) VALUES ("h13", 12, false)', 'different rows may not share the same primary column value' ],
			[ true,  'INSERT INTO table_2 (s, pi, b) VALUES ("h13", 14, true); REPLACE INTO table_2 (s, pi, b) VALUES ("h15", 14, false)', 'a row can be replaced by a row with the same primary column value' ],
			
			// INSERT/REPLACE INTO, SYNTAX AND SEMANTICS: BOOLEAN PRIMARY, NON-ZERO INDEX
			[ true,  'INSERT INTO table_3 (s, pb, i) VALUES ("i1", false, 2)', 'primary column need not be leftmost' ],
			[ true,  'INSERT INTO table_3 (s, i, pb) VALUES ("i3", 4, true)', 'primary column need not be leftmost' ],
			[ false, 'INSERT INTO table_3 (s, i) VALUES ("i5", 6)', 'primary column cannot be omitted' ],
			[ false, 'INSERT INTO table_3 (s, i, pb) VALUES ("i7", 8, null)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_3 (s, i, pb) VALUES ("i9", 10, true)', 'different rows may not share the same primary column value' ],
			[ false, 'INSERT INTO table_3 (s, i, pb) VALUES ("i11", 12, false)', 'different rows may not share the same primary column value' ],
			[ true,  'REPLACE INTO table_3 (s, i, pb) VALUES ("i13", 14, true)', 'a row can be replaced by a row with the same primary column value' ],
			[ true,  'REPLACE INTO table_3 (s, i, pb) VALUES ("i15", 16, false)', 'a row can be replaced by a row with the same primary column value' ],
			
			// INSERT INTO, SYNTAX: SHORT FORM
			[ true,  'INSERT INTO table_1 VALUES ("j1", 2, true)', 'column names can be omitted if all values are ordered' ],
			[ false, 'INSERT INTO table_1 VALUES ("j3", 4, false, null)', 'the number of values must match the number of columns in the schema' ],
			[ false, 'INSERT INTO table_1 VALUES ("j5", 6)', 'the number of values must match the number of columns in the schema' ],
			[ false, 'INSERT INTO table_1 VALUES (null, 7, true)', 'primary column values cannot be null' ],
			[ false, 'INSERT INTO table_1 VALUES (true, 8, "j9")', 'the ordered types of values must match the ordered types of columns in the schema' ],
			[ false, 'INSERT INTO table_1 VALUES ("j10", 11, false); INSERT INTO table_1 VALUES ("j10", 12, true)', 'different rows may not share the same primary column value' ],
			[ true,  'INSERT INTO table_1 VALUES ("j13", 14, false); REPLACE INTO table_1 VALUES ("j13", 15, true)', 'a row can be replaced by a row with the same primary column value' ],
			
			// INSERT INTO, SYNTAX AND SEMANTICS: PUNCTUATION AND TABLE NAME
			[ false, 'INSERT INTO table_1 ps, i, b VALUES ("k1", 2, true)', 'the parentheses are required for the column names when given' ],
			[ false, 'INSERT INTO table_1 (ps, i, b) VALUES "k3", 4, false', 'the parentheses are required for the values' ],
			[ false, 'INSERT INTO table_1 VALUES "k5", 6, false', 'the parentheses are required for the values' ],
			[ false, 'INSERT INTO table_0 (ps, i, b) VALUES ("k7", 8, true)', 'the table name must exist' ],
			
			// DUMP TABLE, SEMANTICS
			[ true,  'DUMP TABLE table_1', 'dump must succeed for valid table' ],
			[ true,  'DUMP TABLE table_2', 'dump must succeed for valid table' ],
			[ true,  'DUMP TABLE table_3', 'dump must succeed for valid table' ],
			[ false, 'DUMP TABLE table_0', 'dump must fail for invalid table' ],
			[ false, 'DROP TABLE table_1; DUMP TABLE table_1', 'dump must fail for dropped table' ],
			
			// SHOW TABLES, CUMULATIVE
			[ true,  'SHOW TABLES', 'row counts for show tables must be correct' ]
		]
		
		computed_schemas = [
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':null],
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':null],
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':null],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':null],
			null,
			null,
			null,
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			null,
			null,
			['column_types':['string', 'integer'], 'column_names':['table_name', 'row_count'], 'primary_column':0, 'table_name':null],
		]
	
		computed_states = [
			[:],
			[:],
			[:],
			['a1':['a1', 2, false]],
			['a4':['a4', 3, true]],
			['a5':['a5', 6, false]],
			['a8':['a8', 7, true]],
			['a10':['a10', 9, false]],
			['b1':['b1', 2, null]],
			['b3':['b3', null, true]],
			['b5':['b5', 4, null]],
			['b6':['b6', null, false]],
			['b7':['b7', null, null]],
			null,
			null,
			null,
			null,
			null,
			['0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null]],
			['456':['456', null, null]],
			['null':['null', null, null]],
			['':['', null, null]],
			null,
			null,
			null,
			['e1':['e1', -200, null]],
			['e3':['e3', 0, null]],
			['e4':['e4', 500, null]],
			['e6':['e6', 700, null]],
			['e8':['e8', null, null]],
			null,
			null,
			null,
			null,
			['f1':['f1', null, true]],
			['f2':['f2', null, false]],
			['f3':['f3', null, true]],
			['f4':['f4', null, false]],
			['f5':['f5', null, null]],
			null,
			null,
			null,
			null,
			null,
			null,
			['g6':['g6', 8, false]],
			[2:['h1', 2, true]],
			[3:['h4', 3, false]],
			[6:['h5', 6, false]],
			[8:['h7', 8, false]],
			null,
			null,
			null,
			null,
			[14:['h15', 14, false]],
			[(false):['i1', 2, false]],
			[(true):['i3', 4, true]],
			null,
			null,
			null,
			null,
			[(true):['i13', 14, true]],
			[(false):['i15', 16, false]],
			['j1':['j1', 2, true]],
			null,
			null,
			null,
			null,
			null,
			['j13':['j13', 15, true]],
			null,
			null,
			null,
			null,
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 12:['h11', 12, true], 6:['h5', 6, false], 14:['h15', 14, false]],
			[(false):['i15', 16, false], (true):['i13', 14, true]],
			null,
			null,
			['table_2':['table_2', 6], 'table_3':['table_3', 2]],
		]
	
		stored_schemas = [
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			null,
			['column_types':['string', 'integer', 'boolean'], 'column_names':['ps', 'i', 'b'], 'primary_column':0, 'table_name':'table_1'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'pi', 'b'], 'primary_column':1, 'table_name':'table_2'],
			['column_types':['string', 'integer', 'boolean'], 'column_names':['s', 'i', 'pb'], 'primary_column':2, 'table_name':'table_3'],
			null,
			null,
			null,
		]
	
		stored_states = [
			[:],
			[:],
			[:],
			['a1':['a1', 2, false]],
			['a1':['a1', 2, false], 'a4':['a4', 3, true]],
			['a1':['a1', 2, false], 'a5':['a5', 6, false], 'a4':['a4', 3, true]],
			['a1':['a1', 2, false], 'a4':['a4', 3, true], 'a5':['a5', 6, false], 'a8':['a8', 7, true]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'a4':['a4', 3, true], 'a5':['a5', 6, false], 'a8':['a8', 7, true]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'a4':['a4', 3, true], 'a5':['a5', 6, false], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'a5':['a5', 6, false], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a1':['a1', 2, false], 'a10':['a10', 9, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true], 'b1':['b1', 2, null]],
			['a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'e1':['e1', -200, null], 'f2':['f2', null, false], 'f3':['f3', null, true], 'e3':['e3', 0, null], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'e4':['e4', 500, null], 'f5':['f5', null, null], 'a1':['a1', 2, false], 'b3':['b3', null, true], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'b5':['b5', 4, null], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'b6':['b6', null, false], 'null':['null', null, null], 'b7':['b7', null, null], '456':['456', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			[2:['h1', 2, true]],
			[2:['h1', 2, true], 3:['h4', 3, false]],
			[2:['h1', 2, true], 6:['h5', 6, false], 3:['h4', 3, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 6:['h5', 6, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 6:['h5', 6, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 6:['h5', 6, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 6:['h5', 6, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 12:['h11', 12, true], 6:['h5', 6, false]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 12:['h11', 12, true], 6:['h5', 6, false], 14:['h15', 14, false]],
			[(false):['i1', 2, false]],
			[(false):['i1', 2, false], (true):['i3', 4, true]],
			[(false):['i1', 2, false], (true):['i3', 4, true]],
			[(false):['i1', 2, false], (true):['i3', 4, true]],
			[(false):['i1', 2, false], (true):['i3', 4, true]],
			[(false):['i1', 2, false], (true):['i3', 4, true]],
			[(false):['i1', 2, false], (true):['i13', 14, true]],
			[(false):['i15', 16, false], (true):['i13', 14, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			null,
			['':['', null, null], 'a10':['a10', 9, false], '0 d1+d2? d3! ':['0 d1+d2? d3! ', null, null], 'j1':['j1', 2, true], 'j10':['j10', 11, false], 'f1':['f1', null, true], 'f2':['f2', null, false], 'f3':['f3', null, true], 'j13':['j13', 15, true], 'f4':['f4', null, false], 'b1':['b1', 2, null], 'f5':['f5', null, null], 'b3':['b3', null, true], 'b5':['b5', 4, null], 'b6':['b6', null, false], 'b7':['b7', null, null], '456':['456', null, null], 'e1':['e1', -200, null], 'g3':['g3', 4, true], 'e3':['e3', 0, null], 'e4':['e4', 500, null], 'g6':['g6', 8, false], 'a1':['a1', 2, false], 'e6':['e6', 700, null], 'a4':['a4', 3, true], 'e8':['e8', null, null], 'a5':['a5', 6, false], 'null':['null', null, null], 'a8':['a8', 7, true]],
			[8:['h7', 8, false], 2:['h1', 2, true], 3:['h4', 3, false], 12:['h11', 12, true], 6:['h5', 6, false], 14:['h15', 14, false]],
			[(false):['i15', 16, false], (true):['i13', 14, true]],
			null,
			null,
			null,
		]
	}
}